select * from Address
select * from Company
select * from PersonClient
select * from WorkshopReservationDetails
select * from EarlyBirdDiscount
select * from DayReservationDetails
select * from Person
select * from DayReservation
select * from WorkshopReservation
select * from Reservation
select * from Client
select * from Day
select * from WorkshopInstance
select * from WorkshopType
select * from Conference