delete from Address
delete from Company
delete from PersonClient
delete from WorkshopReservationDetails
delete from EarlyBirdDiscount
delete from DayReservationDetails
delete from Person
delete from DayReservation
delete from WorkshopReservation
delete from Reservation
delete from Client
delete from Day
delete from WorkshopInstance
delete from WorkshopType
delete from Conference